{
  "openapi": "3.0.0",
  "info": {
    "title": "Delivery Tracker API",
    "description": "API responsavel por guardar as entregas",
    "termsOfService": "Interativa Telecom",
    "contact": {
      "email": "joao.silva@interativa.com.br",
      "celular": "(86)981320524"
    },
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "http://localhost:${PORT}${VERSION}",
      "description": "Api de desenvolvimento"
    }
  ],
  "paths": {
    "/delivery": {
      "post": {
        "summary": "Gravação da entrega",
        "description": "Essa rota desempenha um papel crucial de salvar as entregas feitas pelo entegrado",
        "tags": ["DELIVERY"],
        "security": [{ "bearerAuth": [] }],
        "requestBody": {
          "content": {
            "application/json": {
              "example": {
                "deliveredByName": "entregado test",
                "deliveredByEmail": "test@interativabr.com.br",
                "recipient": {
                  "cpf_cnpj": "0912224311",
                  "boletus_id": 3456434,
                  "email?": "não é obrigatórios",
                  "number?": "não é obrigatórios",
                  "someoneAtHome": true
                },
                "latitude": 4355654,
                "longitude": 435536,
                "imageReference": "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Gravou a entrega com sucesso!",
            "content": {
              "application/json": {
                "example": {
                  "delivery": {
                    "deliveredByName": "entregado test",
                    "deliveredByEmail": "test@interativabr.com.br",
                    "recipient": {
                      "cpf_cnpj": "0912224311",
                      "boletus_id": 3456434,
                      "email": null,
                      "number": null,
                      "someoneAtHome": true
                    },
                    "latitude": 4355654,
                    "longitude": 435536,
                    "imageReference": "https://${AZURE_STORAGE_NAME}.blob.core.windows.net/${AZURE_CONTEINER_NAME}/testImage.png",
                    "deliveryDate": "2023-12-01"
                  }
                }
              }
            }
          },
          "401": {
            "description": "Error de altenticação",
            "content": {
              "application/json": {
                "example": {
                  "error": "Voçê não esta altenticado!"
                }
              }
            }
          },
          "400": {
            "description": "Erro no corpo da requisição",
            "content": {
              "application/json": {
                "example": [
                  {
                    "error": "Não foi possivel registra a entrega: Adicine o email do entregador!"
                  },
                  {
                    "error": "Não foi possivel registra a entrega: Adicione o nome do entregador!"
                  },
                  {
                    "error": "Não foi possivel registra a entrega: Adicione A imagem de referencia!"
                  },
                  {
                    "error": "Não foi possivel registra a entrega: Falata a longitude e latitude!"
                  },
                  {
                    "error": "Não foi possivel registra a entrega: Cpf ou CNPJ do cliente é necessario!"
                  },
                  {
                    "error": "Não foi possivel registra a entrega: id do boleto é necessario!"
                  },
                  {
                    "error": "cpf ou cnpj invalido!"
                  },
                  {
                    "error": "cpf invalido!"
                  },
                  {
                    "error": "cnpj invalido!"
                  },
                  {
                    "error": "Boleto já adicinado"
                  },
                  {
                    "error": "formato de email invalido"
                  }
                ]
              }
            }
          },
          "500": {
            "description": "Error interno do servido, caso aparece algum fora do exemplo deve ser revisto no codigo",
            "content": {
              "application/json": {
                "example": {
                  "error": "Não foi possivel registra a entrega"
                }
              }
            }
          }
        }
      },
      "get": {
        "summary": "Validaçao de cpf do cliente",
        "description": "Essa rota desempenha um papel crucial de validar o cpf do cliente",
        "tags": ["DELIVERY"],
        "parameters": [
          {
            "in": "query",
            "name": "cpf_cnpj",
            "description": "Adicione o cpf de um dos cliente da interativa",
            "require": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "security": [{ "bearerAuth": [] }],
        "responses": {
          "200": {
            "description": "Validou o cliente com sucesso",
            "content": {
              "application/json": {
                "example": {
                  "client": {
                    "id": "1234553256443526543745625",
                    "razao": "Um cliente test",
                    "endereco": "Rua test",
                    "email": "test@interativa.com.br"
                  }
                }
              }
            }
          },
          "401": {
            "description": "Error de altenticação ou validação",
            "content": {
              "application/json": {
                "example": [
                  { "error": "Voçê não esta altenticado!" },
                  {
                    "error": "Cliente invalido"
                  }
                ]
              }
            }
          },
          "400": {
            "description": "Erro na query da requisição",
            "content": {
              "application/json": {
                "example": {
                  "error": "Não foi possivel busca o cliente"
                }
              }
            }
          },
          "500": {
            "description": "Error interno do servido, caso aparece algum fora do exemplo deve ser revisto no codigo",
            "content": {
              "application/json": {
                "example": {
                  "error": "Erro ineserado"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  }
}
